import { type IStep, VisualNode } from "@dronecad/core";
import { MultistepCommand } from "../multistepCommand";
export declare class ArrayCommand extends MultistepCommand {
    private _planeAngle;
    private _meshId;
    protected models?: VisualNode[];
    protected positions?: number[];
    get isGroup(): boolean;
    set isGroup(value: boolean);
    get circularPattern(): boolean;
    set circularPattern(value: boolean);
    get count(): number;
    set count(value: number);
    get numberX(): number;
    set numberX(value: number);
    get numberY(): number;
    set numberY(value: number);
    get numberZ(): number;
    set numberZ(value: number);
    private ensureSelectedModels;
    protected canExcute(): Promise<boolean>;
    private collectionPosition;
    afterExecute(): void;
    private removeMesh;
    private resetMesh;
    private readonly updatePosition;
    private getBoxTransforms;
    private getArcMatrixs;
    protected getSteps(): IStep[];
    private readonly getRadiusData;
    private readonly circlePreview;
    private readonly getAngleData;
    private anglePreview;
    private angleValidator;
    private readonly vectorArrayStepData;
    private readonly pointOnAxisArray;
    private boxArrayMatrixs;
    private boxPlaneInfo;
    protected executeMainTask(): void;
    private cloneNodes;
}
